Update Step_4

diff --git a/Step_4 b/Step_4
--- a/Step_4
+++ b/Step_4
@@ -1,1 +1,58 @@
+################Step 3: Merge and Filter VCF Files################
+# Function: This script merges individual VCF files, applies PLINK filters, and converts the files to PLINK format.
+# It will be helpful to run this as an sh file.
 
+#!/bin/bash
+#PBS -q normal
+#PBS -l select=1:ncpus=1:mem=100G
+#PBS -l walltime=96:00:00
+#PBS -N Merge_vcf
+#PBS -P Personal
+
+# Define directories
+VCF_DIR="/home/users/nus/aleemj/scratch/Arugula/vcf_files" # Directory containing VCF files
+PLINK_DIR="/home/users/nus/aleemj/scratch/Arugula/plink_files" # Directory for PLINK files
+PLINK="/home/users/nus/aleemj/plink" # Path to the PLINK executable
+
+# Create directories only if they do not exist
+[ ! -d "$PLINK_DIR" ] && mkdir -p "$PLINK_DIR"
+
+# Load bcftools module
+module load bcftools
+
+# Change to the VCF directory
+cd "$VCF_DIR" || { echo "Failed to change directory to $VCF_DIR"; exit 1; }
+
+# Call variants using BCFtools
+echo "bcftools mpileup -Ou -q 20 -Q 30 -f $REFERENCE_GENOME $BAM_DIR/*.bam | bcftools call -mv -Oz -o $VCF_DIR/output.vcf"
+
+# Index the VCF file
+echo "bcftools index $VCF_DIR/${SAMPLE_NAME}.bcf"
+
+# Merge all VCF files in the directory
+#MERGED_VCF="$PLINK_DIR/merged_samples.vcf.gz" # Change name if necessary
+#bcftools merge -0 --missing-to-ref -Oz -o "$MERGED_VCF" *.bcf
+
+# Index the merged VCF file
+#bcftools index "$MERGED_VCF"
+
+# Convert the merged VCF to PLINK format
+$PLINK --vcf "$MERGED_VCF" --keep-allele-order --allow-extra-chr --allow-no-sex --double-id --make-bed --out "$PLINK_DIR/filtered_samples_temp"
+
+# Apply SNPs only filter
+$PLINK --bfile "$PLINK_DIR/filtered_samples_temp" --keep-allele-order --allow-extra-chr --allow-no-sex --snps-only --make-bed --out "$PLINK_DIR/filtered_samples_snps"
+
+# Apply missing genotype filter
+$PLINK --bfile "$PLINK_DIR/filtered_samples_snps" --keep-allele-order --allow-extra-chr --allow-no-sex --geno 0.1 --make-bed --out "$PLINK_DIR/filtered_samples_snps_geno"
+
+# Apply MAF filter
+$PLINK --bfile "$PLINK_DIR/filtered_samples_snps_geno" --keep-allele-order --allow-extra-chr --allow-no-sex --maf 0.05 --make-bed --out "$PLINK_DIR/filtered_samples_snps_geno_maf"
+
+# Deal with duplicate variant ID names
+$PLINK --bfile "$PLINK_DIR/filtered_samples_snps_geno_maf" --keep-allele-order --allow-extra-chr --allow-no-sex --set-missing-var-ids @:# --make-bed --out "$PLINK_DIR/final"
+
+# Create a PED file from the BED file
+$PLINK --bfile "$PLINK_DIR/final" --keep-allele-order --allow-no-sex --allow-extra-chr --recode --tab --out "$PLINK_DIR/final"
+
+# Create a final VCF file from the BED file
+$PLINK --bfile "$PLINK_DIR/final" --keep-allele-order --allow-no-sex --allow-extra-chr --recode vcf --out "$PLINK_DIR/final"
